### ISSUE TITLE
Very slow

### ISSUE THREAD

**Issue by yazeed-mohammad** [Mohamedfaroouk/widget_to_marker#3]
Thank you very much for this pretty package.
I faced an issue when widget rendering its very very slow.

is there any fix for this issue ?

**Comment by Mohamedfaroouk** [comment]
can u share ur code ?
you may use a en expensive widget to convert

**Comment by yazeed-mohammad** [comment]
I have 20 markers 

```
class MarkerWidget extends StatelessWidget {
  const MarkerWidget({super.key, required this.item});

  final Location item;

  @override
  Widget build(BuildContext context) {
    return SizedBox(
      height: 80.w,
      child: Column(
        mainAxisAlignment: MainAxisAlignment.start,
        children: [
          Container(
            height: 60.h,
            width: 60.w,
            padding: const EdgeInsets.all(6),
            decoration: BoxDecoration(
                color: AppColors.white,
                shape: BoxShape.circle,
                border: Border.all(color: AppColors.brown, width: 6.w),
                image: DecorationImage(image: CachedNetworkImageProvider(item.businessLogo!.filePath!), fit: BoxFit.contain)),
          ),
          Container(height: 19.h, width: 6.w, color: AppColors.brown),
        ],
      ),
    );
  }
}

```

**Comment by Mohamedfaroouk** [comment]
I believe the reason for the slow performance you are experiencing is due to the use of NetworkImage, which requires rendering the image from the network each time it is used in a widget. This can result in a delay when displaying the image in multiple widgets, as it must be fetched from the network each time (20 time in your case).

To improve the performance of your app, my suggestion would be to download the image once and store it as bytes. You could then use a MemoryImage to load the image into each widget, avoiding the need for repeated fetching from the network.
