### ISSUE TITLE
Marker changes the position when map is zoomed in or out.

### ISSUE THREAD

**Issue by SabinTulips** [Mohamedfaroouk/widget_to_marker#7]
Thanks for the plugin, it works great except, if I zoom in or out the map, the marker changes its position. Am I missing something? How can this be solved.

Thanks

**Comment by Mohamedfaroouk** [comment]
The issue is caused by the main marker (image or widget) having excessive white space surrounding it. In the case of an image, this white space corresponds to the width and height of the original image. To resolve this, it is necessary to crop the image so that it aligns closely with its boundaries, removing any unnecessary empty space.

When dealing with a widget, the extra padding needs to be eliminated. This involves adjusting the widget's layout or style settings to ensure that there is no excessive space surrounding it.

By addressing these aspects, you can achieve a more visually appealing and precise representation of the main marker, be it an image or a widget.

**Comment by RaagullSakthivelV** [comment]
**class to which I pass text and image**


`class TextOnImage extends StatelessWidget {
  const TextOnImage({
    required this.text,
    required this.imagePath,
    super.key,
  });
  final String text;
  final String imagePath;

  @override
  Widget build(BuildContext context) => Stack(
    alignment: Alignment.center,
    children: <Widget>[
      Image(
        image: AssetImage(
          imagePath,
        ),
        height: 150,
        width: 150,
      ),
      Text(
        text,
        style: const TextStyle(
            color: Colors.white,
            fontSize: 12,
            fontWeight: FontWeight.w700),
      ),
    ],
  );
}

`

**marker where I use the package from the above class**
 Marker(

        markerId: MarkerId(
          userLocations?.data.indexOf(userData).toString() ??
              markers.length.toString(),
        ),
        position: userData.availability
            ? LatLng(
                userData.liveLocation?.x ?? 0.0,
                userData.liveLocation?.y ?? 0.0,
              )
            : LatLng(
                userData.liveLocation?.x ?? 0.0,
                userData.liveLocation?.y ?? 0.0,
              ),
        infoWindow: InfoWindow(
          title: userData.fullName,
        ),
        icon: await TextOnImage(
        text: userData.fullName.split("").first,
        imagePath: ConstantImage.userMarker,
      ).toBitmapDescriptor(),
        zIndex: 2,
        
       anchor:const Offset(0.6, 0.8), // Adjust the anchor here
        onTap: () async {
          debugPrint("call from updatePlaceList");
        },
      )

**what should I change to stop the marker from changing its position while zooming in**

https://github.com/user-attachments/assets/e80fd4d8-fff6-41bb-8d73-a62d338938b8

**These are the two images I use for markers** 
![base](https://github.com/user-attachments/assets/7e5ab0ea-7f3b-42b1-972b-2e3a51551c56)
![live](https://github.com/user-attachments/assets/40b99693-4507-4d2a-8f67-8ae893afbd83)
